import type { ArticleInput } from './types.js'

// Compact cleaned mock content adapted from the local SkillsBench Markdown notes.
export const mockArticle: ArticleInput = {
  id: 'mock-skillsbench-cleaned-article',
  title: 'SkillsBench: Evaluating Agent Skills Across Diverse Tasks',
  url: 'https://skillsbench.ai',
  source: 'Local mock corpus: repos/skillsbench-report.md',
  author: 'SkillsBench research team',
  publishedAt: '2026-03-16',
  language: 'en',
  contentMarkdown: [
    '# SkillsBench: Evaluating Agent Skills Across Diverse Tasks',
    '',
    '## Abstract',
    '',
    'Agent skills are reusable packages of procedural knowledge that can be injected into an LLM agent at inference time. They usually contain instructions, workflow steps, examples, templates, or executable resources. SkillsBench studies whether these packages actually improve agent performance across realistic tasks instead of only adding more context.',
    '',
    'The benchmark evaluates 84 tasks across 11 domains under paired conditions: no skills, curated skills, and self-generated skills. The study reports that curated skills improve average pass rate by 16.2 percentage points across seven agent-model configurations, while self-generated skills provide little or negative benefit on average.',
    '',
    '## Motivation',
    '',
    'Modern LLM agents can operate tools, inspect files, run commands, and complete multi-step tasks. However, broad model capability does not guarantee knowledge of domain-specific procedures. A model may understand a problem conceptually but still miss the exact workflow, file format, verifier expectation, or operational convention needed to finish the task.',
    '',
    'Skills offer a modular alternative to fine-tuning. Instead of changing model weights, a skill package gives the agent reusable procedural guidance at runtime. This makes skills easy to edit, version, share, and apply across different agent harnesses. The open question is how much they help in practice and when they become unnecessary or harmful.',
    '',
    '## Benchmark Design',
    '',
    'SkillsBench treats skills as first-class evaluation artifacts. Each task is packaged with an isolated environment, deterministic verifier, oracle solution, and optional skills directory. The task instructions do not tell the agent which skill to use, so the evaluation measures whether the harness and model can discover and apply relevant procedural guidance.',
    '',
    'The task set covers software engineering, office work, natural science, cybersecurity, finance, robotics, manufacturing, energy, mathematics, healthcare, and media production. Contributors submitted candidate tasks, and maintainers filtered them through structural validation, oracle execution, leakage checks, and human review.',
    '',
    'A valid skill must describe how to approach a class of tasks rather than provide an answer to one instance. It may include a SKILL.md file, scripts, templates, examples, and reference material. It should avoid task-specific filenames, constants, exact command sequences, or expected outputs that would leak the solution.',
    '',
    '## Evaluation Setup',
    '',
    'The benchmark runs each task under three conditions. In the no-skills condition, the agent receives only the task instruction. In the curated-skills condition, the relevant skills package is available in the environment. In the self-generated-skills condition, the agent is prompted to produce procedural guidance before solving the task, but no human-curated skill is provided.',
    '',
    'The study compares commercial agent harnesses such as Claude Code, Gemini CLI, and Codex CLI across seven model-harness configurations. Deterministic verifiers produce pass or fail outcomes, and full trajectories are logged for later analysis.',
    '',
    '## Key Findings',
    '',
    '- Curated skills provide substantial but variable gains. Average pass rate rises from 24.3 percent without skills to 40.6 percent with curated skills.',
    '- Self-generated skills do not match curated skills. On average they slightly underperform the no-skills baseline, suggesting that effective procedural knowledge still benefits from human curation.',
    '- Skill benefits differ by domain. Healthcare and manufacturing show large gains, while software engineering and mathematics show smaller aggregate gains.',
    '- More context is not always better. Focused skills with a small number of modules outperform broad documentation, and overly comprehensive skills can increase cognitive overhead.',
    '- Skills can help smaller models compete with larger models on procedural tasks, but the result depends on the harness, the task, and the quality of the skill package.',
    '',
    '## Design Implications',
    '',
    'The results suggest that skill authors should prefer concise, stepwise guidance over exhaustive reference material. A useful skill should expose the decision points an agent must follow, provide a small number of representative examples, and leave room for the agent to adapt details to the current repository or task context.',
    '',
    'Skills should also be evaluated under paired conditions. A positive example is not enough: maintainers need to compare with-skill and no-skill trajectories, inspect failures, and measure whether the skill improves correctness, reduces wasted exploration, or merely increases token usage.',
    '',
    '## Limitations',
    '',
    'SkillsBench focuses on terminal-based, containerized tasks, so its results may not transfer directly to GUI agents, long-horizon workflows, or multi-agent settings. The measured gains also depend on the agent harness and model versions used during evaluation.',
    '',
    'Another limitation is causal attribution. Adding a skill increases context length, and some gains may come from extra relevant text rather than the skill structure itself. Stronger controls, including length-matched distractors and retrieval-only documentation baselines, are needed to isolate which skill components drive improvements.',
    '',
    '## Conclusion',
    '',
    'SkillsBench shows that curated agent skills can improve LLM agent performance, but the effect is not universal. Skills work best when they encode reusable procedures for domains where the base model lacks reliable operational knowledge. They are less useful when the model already has strong priors, and they can hurt when broad or mismatched guidance distracts the agent from the actual task.',
  ].join('\n'),
}

export default mockArticle
